### ISSUE TITLE
Plugin fails to split into tokens for later requests

### ISSUE THREAD

**Issue by mjunaidmuzammil** [CitrineInformatics/plugin-plussign#2]
Hi,
I tried out your piece of code with different ES versions including 1.0 & 1.7. I observed that the plugin successfully splits into token for the first request. However, for the next requests it fails to split into tokens.

The output that I obtain for the same string (i.e. "This+is++some+text") passed 2nd time is,

{
  "tokens" : [ ]
}

**Comment by kjaym** [comment]
Good catch! PlusSignTokenizer.java has been updated with a reset method that fixes this. Tested in 1.7.
